"use client";
import { FormEvent, useState } from "react";

type Offer={id:string;store:string;title:string;price:number;shipping:number|null;url:string;image:string;condition:string;stock:number|null};
type SearchResponse={offers:Offer[];source:string;sources?:string[];fetchedAt:string;error?:string};
const money=(value:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);

export default function Home(){
 const [query,setQuery]=useState(""); const [searched,setSearched]=useState(""); const [offers,setOffers]=useState<Offer[]>([]); const [sources,setSources]=useState<string[]>([]); const [source,setSource]=useState(""); const [fetchedAt,setFetchedAt]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [freeShipping,setFreeShipping]=useState(false); const [condition,setCondition]=useState("all");
 const visible=offers.filter(o=>!freeShipping||o.shipping===0).filter(o=>condition==="all"||o.condition===condition).sort((a,b)=>(a.price+(a.shipping??0))-(b.price+(b.shipping??0))); const best=visible[0];
 async function search(event?:FormEvent,quick?:string){event?.preventDefault();const term=(quick??query).trim();if(term.length<2)return;setQuery(term);setSearched(term);setLoading(true);setError("");setOffers([]);setSources([]);setSource("");try{const response=await fetch(`/api/search?q=${encodeURIComponent(term)}`);const data:SearchResponse=await response.json();if(!response.ok)throw new Error(data.error||"No fue posible consultar la fuente");setOffers(data.offers);setSources(data.sources||[]);setSource(data.source);setFetchedAt(data.fetchedAt)}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible completar la búsqueda")}finally{setLoading(false)}}
 return <main>
  <header className="topbar"><a className="logo" href="#top"><span>Compara</span>Ya<i>.</i></a><nav><a href="#fuentes">Fuentes</a><a href="#como-funciona">Cómo funciona</a><span className="live-badge"><b/> Datos verificables</span></nav></header>
  <section className="hero" id="top"><div className="hero-copy"><span className="eyebrow"><b>●</b> COMPARADOR DE PRECIOS EN CHILE</span><h1>Busca una vez.<br/><em>Compra mejor.</em></h1><p>Resultados obtenidos desde fuentes reales. Cada precio conserva su enlace directo y hora de consulta.</p></div><div className="hero-stat"><strong>100%</strong><span>resultados con<br/>fuente identificada</span></div>
   <form className="searchbox" onSubmit={e=>search(e)}><span aria-hidden="true" className="search-icon">⌕</span><label className="sr-only" htmlFor="product-search">Buscar producto</label><input id="product-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="¿Qué quieres encontrar? Ej: PS5, iPhone 16..."/><button disabled={loading}>{loading?"Buscando…":"Comparar precios"}<span>→</span></button></form>
   <div className="quick-searches"><span>Prueba buscando:</span>{["PlayStation 5","Nintendo Switch","iPhone 16","Notebook gamer"].map(item=><button key={item} onClick={()=>search(undefined,item)}>{item}</button>)}</div>
  </section>
  <section className="results-wrap">
   {!searched&&<div className="empty-state"><span>⌕</span><h2>¿Qué estás buscando?</h2><p>Escribe un producto para consultar las fuentes conectadas. No mostramos precios de demostración.</p></div>}
   {loading&&<div className="empty-state loading"><span/><h2>Consultando publicaciones reales…</h2><p>Estamos ordenando los resultados por precio total.</p></div>}
   {error&&!loading&&<div className="source-error"><b>La búsqueda real aún no está disponible</b><p>{error}</p><small>No se reemplazó la información con datos inventados.</small></div>}
   {!loading&&!error&&searched&&<><div className="results-head"><div><span className="kicker">RESULTADOS REALES PARA</span><h2>“{searched}”</h2><p>{offers.length} publicaciones · {sources.length} {sources.length===1?"tienda":"tiendas"} identificadas · {source} {fetchedAt&&`· ${new Date(fetchedAt).toLocaleString("es-CL")}`}</p></div></div>
    {best?<><article className="winner"><div className="winner-label"><span>★</span> MENOR PRECIO TOTAL</div><div className="product-art real">{best.image?<img src={best.image} alt=""/>:<span>Sin imagen</span>}</div><div className="winner-info"><span className="store-chip">{best.store}</span><h3>{best.title}</h3><p><b>✓</b> Publicación enlazada a su fuente</p><div className="facts"><span>{best.condition==="new"?"Nuevo":"Usado"}</span><span>•</span><span>{best.stock?"Disponible":"Stock no informado"}</span></div></div><div className="winner-price"><small>PRECIO PUBLICADO</small><strong>{money(best.price)}</strong><span>{best.shipping===0?"Envío gratis informado":best.shipping?`Envío: ${money(best.shipping)}`:"Envío por confirmar en tienda"}</span><a className="offer-link" href={best.url} target="_blank" rel="noopener noreferrer">Ver publicación <b>↗</b></a></div></article>
     <div className="toolbar"><div className="filter"><button className={condition==="all"?"selected":""} onClick={()=>setCondition("all")}>Todos</button><button className={condition==="new"?"selected":""} onClick={()=>setCondition("new")}>Nuevos</button><button className={condition==="used"?"selected":""} onClick={()=>setCondition("used")}>Usados</button></div><label className="check"><input type="checkbox" checked={freeShipping} onChange={e=>setFreeShipping(e.target.checked)}/> Envío gratis informado</label></div>
     <div className="offer-list">{visible.map((offer,index)=><article className="offer" key={offer.id}><span className="rank">{String(index+1).padStart(2,"0")}</span><div className="store-mark">{offer.store.slice(0,2).toUpperCase()}</div><div className="offer-info"><span>{offer.store} · Mercado Libre</span><h3>{offer.title}</h3><p>{offer.condition==="new"?"Nuevo":"Usado"} · {offer.stock&&offer.stock>0?"Disponible":"Stock no informado"}</p></div><div className="offer-price"><strong>{money(offer.price)}</strong><span>{offer.shipping===0?"Envío gratis":offer.shipping?`+ ${money(offer.shipping)} envío`:"Envío por confirmar"}</span></div><a className="go" href={offer.url} target="_blank" rel="noopener noreferrer" aria-label={`Abrir ${offer.title}`}>↗</a></article>)}</div></>:<div className="empty-state"><span>—</span><h2>Sin coincidencias</h2><p>No encontramos publicaciones comprables del tipo de producto pedido. Prueba agregando modelo o versión.</p></div>}
   </>}
  </section>
  <section className="sources" id="fuentes"><span className="kicker">COBERTURA REAL</span><h2>Fuentes conectadas</h2><div className="source-card"><div className="store-mark">ST</div><div><b>Catálogo multitienda de SoloTodo</b><p>Ofertas activas con enlace directo a Falabella, Paris, PC Factory, SP Digital y otros comercios disponibles para cada producto.</p></div><span className="connected">Conectada</span></div><div className="source-card"><div className="store-mark">ML</div><div><b>Mercado Libre Chile</b><p>API oficial usada como respaldo cuando el catálogo multitienda no devuelve una coincidencia comprable.</p></div><span className="connected">Conectada</span></div><p className="source-note">Los precios se consultan al buscar y siempre debes confirmarlos en la tienda antes de comprar.</p></section>
  <section className="how" id="como-funciona"><span className="kicker">TRAZABILIDAD</span><h2>Cada precio tiene respaldo</h2><div><article><b>01</b><h3>Consultamos</h3><p>La búsqueda llega a las fuentes habilitadas para Chile.</p></article><article><b>02</b><h3>Normalizamos</h3><p>Ordenamos condición, precio y despacho sin alterar el dato original.</p></article><article><b>03</b><h3>Enlazamos</h3><p>Siempre puedes abrir la publicación original y confirmar antes de comprar.</p></article></div></section>
  <footer><a className="logo" href="#top"><span>Compara</span>Ya<i>.</i></a><p>Sin precios inventados. Sin tiendas ficticias.</p><span>Hecho para Chile 🇨🇱</span></footer>
 </main>
}
